export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const ERROR = "ERROR";
export const ACCOUNT_START_LOADING = "ACCOUNT_START_LOADING";
export const ACCOUNT_END_LOADING = "ACCOUNT_END_LOADING";